spring:
  application:
        name: eureka-service
server:
   port: 8070
eureka:
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    lease-renewal-interval-in-seconds: 2
    lease-expiration-duration-in-seconds: 20
  client:
    registerWithEureka: false
    fetchRegistry: false
    eurekaServerPort: 1111
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    renewal-percent-threshold: 0.49